# Generated by Django 5.0.3 on 2024-04-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('Backa', 'Back: Deadlifts'), ('Backb', 'Back: Pull-ups'), ('Backc', 'Back: Barbell rows'), ('Backd', 'Back: Lat pulldowns'), ('Backe', 'Back: Single-arm dumbbell rows'), ('Backf', 'Back: T-bar rows'), ('Backg', 'Back: Seated cable rows'), ('Backh', 'Back: Dumbbell pullovers'), ('Backi', 'Back: Bent-over dumbbell rows'), ('Backj', 'Back: Hyperextensions'), ('Chesta', 'Chest: Bench press (barbell or dumbbell)'), ('Chestb', 'Chest: Push-ups'), ('Chestc', 'Chest: Incline bench press'), ('Chestd', 'Chest: Chest flyes (cable or dumbbell)'), ('Cheste', 'Chest: Decline bench press'), ('Chestf', 'Chest: Dumbbell pullovers'), ('Chestg', 'Chest: Dips (chest variation)'), ('Chesth', 'Chest: Cable crossovers'), ('Chesti', 'Chest: Machine chest press'), ('Chestj', 'Chest: Incline dumbbell press'), ('Shouldersa', 'Shoulders: Overhead press (barbell or dumbbell)'), ('Shouldersb', 'Shoulders: Dumbbell lateral raises'), ('Shouldersc', 'Shoulders: Front dumbbell raises'), ('Shouldersd', 'Shoulders: Arnold press'), ('Shoulderse', 'Shoulders: Upright rows'), ('Shouldersf', 'Shoulders: Shoulder press machine'), ('Shouldersg', 'Shoulders: Cable lateral raises'), ('Shouldersh', 'Shoulders: Reverse flyes (dumbbell or machine)'), ('Shouldersi', 'Shoulders: Face pulls'), ('Shouldersj', 'Shoulders: Shrugs (barbell or dumbbell)'), ('Legsa', 'Legs: Squats (barbell or dumbbell)'), ('Legsb', 'Legs: Lunges (forward, reverse, or walking)'), ('Legsc', 'Legs: Leg press'), ('Legsd', 'Legs: Deadlifts (conventional or sumo)'), ('Legse', 'Legs: Leg extensions'), ('Legsf', 'Legs: Leg curls (standing or lying)'), ('Legsg', 'Legs: Calf raises (seated or standing)'), ('Legsh', 'Legs: Bulgarian split squats'), ('Legsi', 'Legs: Box jumps'), ('Legsj', 'Legs: Romanian deadlifts'), ('Bicepsa', 'Biceps: Barbell curls'), ('Bicepsb', 'Biceps: Dumbbell curls (standing or seated)'), ('Bicepsc', 'Biceps: Preacher curls (barbell or dumbbell)'), ('Bicepsd', 'Biceps: Hammer curls'), ('Bicepse', 'Biceps: Concentration curls'), ('Bicepsf', 'Biceps: Cable curls'), ('Bicepsg', 'Biceps: Incline dumbbell curls'), ('Bicepsh', 'Biceps: Reverse curls'), ('Bicepsi', 'Biceps: EZ-bar curls'), ('Bicepsj', 'Biceps: Spider curls'), ('Tricepsa', 'Triceps: Tricep dips (parallel bars or bench)'), ('Tricepsb', 'Triceps: Close-grip bench press'), ('Tricepsc', 'Triceps: Tricep pushdowns (cable machine)'), ('Tricepsd', 'Triceps: Skull crushers (barbell or dumbbell)'), ('Tricepse', 'Triceps: Overhead tricep extensions (dumbbell or cable)'), ('Tricepsf', 'Triceps: Tricep kickbacks'), ('Tricepsg', 'Triceps: Diamond push-ups'), ('Tricepsh', 'Triceps: Rope tricep pushdowns'), ('Tricepsi', 'Triceps: Bench dips'), ('Tricepsj', 'Triceps: Tricep rope overhead extension'), ('Absa', 'Abs: Crunches (standard, reverse, or bicycle)'), ('Absb', 'Abs: Planks (standard, side, or weighted)'), ('Absc', 'Abs: Russian twists'), ('Absd', 'Abs: Leg raises (lying or hanging)'), ('Abse', 'Abs: Mountain climbers'), ('Absf', 'Abs: Cable crunches'), ('Absg', 'Abs: Woodchoppers (cable or medicine ball)'), ('Absh', 'Abs: Ab wheel rollouts'), ('Absi', 'Abs: Hanging knee raises'), ('Absj', 'Abs: Flutter kicks')], max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
